app = "discord-pm"
primary_region = "iad"

[build]

[env]
  WEB_PORT = "8080"
  PRIMARY_REGION = "iad"

[mounts]
  source = "discord_pm_data"
  destination = "/app/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
